// @ts-check

/**
 * Sidebar configuration for Docusaurus.
 * This file is auto-generated by scripts/generateSidebar.js
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting started",
      items: [
        {
          type: "doc",
          id: "overview",
          label: "Overview"
        },
        {
          type:  "doc",
          id:    "environmental-setup",
          label: "Environmental Setup"
        },
        {
          type:  "doc",
          id:    "configurations",
          label: "Configuration"
        }
      ]
    },
    {
      type: "category",
      label: "Provider",
      items: [
        {
          type: "doc",
          id: "register-as-provider",
          label: "Becoming a Provider"
        },
        {
          type: "doc",
          id: "provider-authentication",
          label: "Authentication"
        },
        {
          type: "doc",
          id: "provider-settings",
          label: "Settings"
        }
      ]
    },
    {
      type: "category",
      label: "Clients",
      items: [
        {
          type: "doc",
          id: "client-registration",
          label: "Registration"
        },
        {
          type: "doc",
          id: "client-authentication",
          label: "Authentication"
        },
        {
          type: "doc",
          id: "client-settings",
          label: "Settings"
        }
      ]
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "doc",
          id: "accounts",
          label: "Accounts"
        },
        {
          type: "doc",
          id: "payments",
          label: "Payments"
        }
      ]
    }
  ]
};

export default sidebars;
